# Generated by Django 5.1.7 on 2025-08-03 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_remove_blogpost_image_url_alter_blogpost_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='image',
        ),
    ]
