# Generated by Django 5.1.7 on 2025-04-11 14:39

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountprofile",
            name="default_country",
            field=django_countries.fields.CountryField(
                blank=True, max_length=2, null=True
            ),
        ),
        migrations.AddField(
            model_name="accountprofile",
            name="default_county",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name="accountprofile",
            name="default_postcode",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="accountprofile",
            name="default_street_address1",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name="accountprofile",
            name="default_street_address2",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name="accountprofile",
            name="default_town_or_city",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
