# Generated by Django 5.1.7 on 2025-04-13 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_accountprofile_default_country_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="accountprofile",
            old_name="phone_number",
            new_name="default_phone_number",
        ),
    ]
