# Generated by Django 5.1.7 on 2025-07-30 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_phone_number_accountprofile_default_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountprofile',
            old_name='default_phone_number',
            new_name='phone_number',
        ),
    ]
