# Generated by Django 5.1.7 on 2025-03-29 11:08

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_number",
                    models.CharField(
                        editable=False, max_length=32, unique=True),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone_number", models.CharField(max_length=20)),
                (
                    "country",
                    django_countries.fields.CountryField(max_length=2),
                ),
                (
                    "postcode",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("town_or_city", models.CharField(max_length=50)),
                ("street_address1", models.CharField(max_length=100)),
                (
                    "street_address2",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "county",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "delivery_cost",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "order_total",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "grand_total",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10),
                ),
                ("original_bag", models.TextField(default="")),
                ("stripe_pid", models.CharField(default="", max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name="OrderLineItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_size",
                    models.CharField(blank=True, max_length=5, null=True),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "lineitem_total",
                    models.DecimalField(
                        decimal_places=2, editable=False, max_digits=6),
                ),
            ],
        ),
    ]
