# Generated by Django 5.1.7 on 2025-05-31 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HeroImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255)),
                ("image", models.ImageField(upload_to="hero_images/")),
                ("active", models.BooleanField(default=False)),
            ],
        ),
    ]
