# Generated by Django 5.1.5 on 2025-02-09 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DietPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('duration_weeks', models.PositiveIntegerField(blank=True, null=True)),
                ('difficulty_level', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='difficulty_level',
        ),
        migrations.RemoveField(
            model_name='product',
            name='duration_weeks',
        ),
    ]
