# Generated by Django 5.1.5 on 2025-02-09 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_dietplan_remove_product_difficulty_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dietplan',
            name='difficulty_level',
        ),
        migrations.AlterField(
            model_name='dietplan',
            name='duration_weeks',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
