# Generated by Django 5.1.5 on 2025-02-09 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_dietplan_difficulty_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietplan',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='dietplan_images/'),
        ),
    ]
