# Generated by Django 5.1.5 on 2025-02-09 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_fitnessplan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fitnessplan',
            name='difficulty_level',
        ),
        migrations.RemoveField(
            model_name='fitnessplan',
            name='pdf_guide',
        ),
    ]
