# Generated by Django 5.1.7 on 2025-07-30 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('fitness_plans', 'Fitness Plans'), ('diet_plans', 'Diet Plans'), ('eco_friendly_activewear', 'Eco-Friendly Activewear'), ('recycled_fitness_gear', 'Recycled Fitness Gear'), ('vegan_supplements', 'Vegan Supplements'), ('biodegradable_accessories', 'Biodegradable Accessories')], max_length=50),
        ),
    ]
