# Generated by Django 4.2.8 on 2025-02-26 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DietPlan',
        ),
        migrations.DeleteModel(
            name='FitnessPlan',
        ),
        migrations.RemoveField(
            model_name='product',
            name='has_sizes',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_type',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('fitness_plans', 'Fitness Plans'), ('diet_plans', 'Diet Plans'), ('eco_friendly_activewear', 'Eco-Friendly Activewear'), ('recycled_fitness_gear', 'Recycled Fitness Gear'), ('vegan_supplements', 'Vegan Supplements'), ('biodegradable_accessories', 'Biodegradable Accessories')], max_length=50, unique=True),
        ),
    ]
